# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1365605395);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1367420480);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 9);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.buildID", "20130326150557");
user_pref("browser.startup.homepage_override.mstone", "20.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1365691794695");
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1367420421988");
user_pref("datareporting.policy.firstRunTime", "1365605394694");
user_pref("datareporting.sessions.current.activeTicks", 10);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1081);
user_pref("datareporting.sessions.current.main", 93);
user_pref("datareporting.sessions.current.sessionRestored", 1145);
user_pref("datareporting.sessions.current.startTime", "1367420359524");
user_pref("datareporting.sessions.current.totalTime", 141168);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.0", "{\"s\":1365605394239,\"a\":14,\"t\":95410,\"c\":true,\"m\":69,\"fp\":1587,\"sr\":1654}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1365613535070,\"a\":9,\"t\":54839,\"c\":true,\"m\":91,\"fp\":1327,\"sr\":1354}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1365712628370,\"a\":8,\"t\":73167,\"c\":true,\"m\":177,\"fp\":3209,\"sr\":4554}");
user_pref("dom.mozApps.used", true);
user_pref("dom.w3c_touch_events.expose", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:20.0");
user_pref("extensions.installCache", "[{\"name\":\"app-system-local\",\"addons\":{\"{23fcfd51-4958-4f00-80a3-ae97e717ed8b}\":{\"descriptor\":\"/Library/Application Support/Mozilla/Extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{23fcfd51-4958-4f00-80a3-ae97e717ed8b}\",\"mtime\":1362284899000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/Applications/Firefox.app/Contents/MacOS/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1365430677000}}}]");
user_pref("extensions.lastAppVersion", "20.0");
user_pref("extensions.lastPlatformVersion", "20.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/plugin");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20130326150557");
user_pref("gecko.mstone", "20.0");
user_pref("general.warnOnAboutConfig", false);
user_pref("gfx.blacklist.webgl.msaa", 4);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 100664);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1367420359);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1368197401);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
